/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conntroller;

import Dao.assetsClassDao;
import Dao.inventoryListDao;
import Methods.iniTable;
import Methods.setupComponent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.assetsClass;
import model.inventoryList;

/**
 *
 * @author luther
 */
public class inventoryListUI extends javax.swing.JFrame {

    /**
     * Creates new form inventoryListUI
     */
    public inventoryListUI() {
        initComponents();
        setCenter();
        
        iniTable.iniInvListTable(inv_List_Table);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errMsg_jDialog = new javax.swing.JDialog();
        modifyInvItem_JFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        purchase_jLabel = new javax.swing.JLabel();
        purchase_jTextField = new javax.swing.JTextField();
        comName_jLabel = new javax.swing.JLabel();
        comName_jTextField = new javax.swing.JTextField();
        depart_jLabel = new javax.swing.JLabel();
        depart_jTextField = new javax.swing.JTextField();
        invNum_jLabel = new javax.swing.JLabel();
        invNum_jTextField = new javax.swing.JTextField();
        invName_jLabel = new javax.swing.JLabel();
        invName_jTextField = new javax.swing.JTextField();
        invModel_jLabel = new javax.swing.JLabel();
        invModel_jTextField = new javax.swing.JTextField();
        invQuantity_jLabel = new javax.swing.JLabel();
        invQuantity_jTextField = new javax.swing.JTextField();
        location_jLabel = new javax.swing.JLabel();
        location_jTextField = new javax.swing.JTextField();
        remark_jLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        remark_jTextArea = new javax.swing.JTextArea();
        keeper_jLabel = new javax.swing.JLabel();
        keeper_jTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        InvID_jLabel = new javax.swing.JLabel();
        invID_jTextField = new javax.swing.JTextField();
        addInvItem_jFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AssetClass_jComboBox = new javax.swing.JComboBox<>();
        AssetClass_jLabel = new javax.swing.JLabel();
        ComCode_jLabel = new javax.swing.JLabel();
        ComCode_jComboBox = new javax.swing.JComboBox<>();
        Accounting_jLabel = new javax.swing.JLabel();
        Accounting_jComboBox = new javax.swing.JComboBox<>();
        ClassCode_jLabel = new javax.swing.JLabel();
        ClassCode_jComboBox = new javax.swing.JComboBox<>();
        invCheck_btn = new javax.swing.JButton();
        InvCode_TF = new javax.swing.JTextField();
        ac1_RB = new javax.swing.JRadioButton();
        ac2_RB = new javax.swing.JRadioButton();
        AssetClass_TF = new javax.swing.JTextField();
        ComCode_TF = new javax.swing.JTextField();
        Accounting_TF = new javax.swing.JTextField();
        ClassCode_TF = new javax.swing.JTextField();
        assetClass_BG = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        queryInvList_btn = new javax.swing.JButton();
        modifyInvItem_btn = new javax.swing.JButton();
        addInvItem_btn = new javax.swing.JButton();
        scrappedInvItem_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inv_List_Table = new javax.swing.JTable();

        errMsg_jDialog.setFont(new java.awt.Font("標楷體", 0, 16)); // NOI18N
        errMsg_jDialog.setLocation(new java.awt.Point(0, 0));
        errMsg_jDialog.setLocationByPlatform(true);
        errMsg_jDialog.setSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout errMsg_jDialogLayout = new javax.swing.GroupLayout(errMsg_jDialog.getContentPane());
        errMsg_jDialog.getContentPane().setLayout(errMsg_jDialogLayout);
        errMsg_jDialogLayout.setHorizontalGroup(
            errMsg_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        errMsg_jDialogLayout.setVerticalGroup(
            errMsg_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        modifyInvItem_JFrame.setResizable(false);

        jLabel2.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        jLabel2.setText("詳細資料");

        jPanel3.setPreferredSize(new java.awt.Dimension(150, 30));

        purchase_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        purchase_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchase_jLabel.setText("購入日期");
        purchase_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        purchase_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        purchase_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        purchase_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        purchase_jTextField.setPreferredSize(new java.awt.Dimension(150, 30));

        comName_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        comName_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comName_jLabel.setText("公司別");
        comName_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        comName_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        comName_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        comName_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        comName_jTextField.setPreferredSize(new java.awt.Dimension(200, 30));

        depart_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        depart_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depart_jLabel.setText("歸屬部門");
        depart_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        depart_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        depart_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        depart_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        depart_jTextField.setPreferredSize(new java.awt.Dimension(200, 30));

        invNum_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invNum_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invNum_jLabel.setText("財產編號");
        invNum_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        invNum_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        invNum_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invNum_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        invNum_jTextField.setPreferredSize(new java.awt.Dimension(350, 30));

        invName_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invName_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invName_jLabel.setText("財產名稱");
        invName_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        invName_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        invName_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invName_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        invName_jTextField.setPreferredSize(new java.awt.Dimension(600, 30));

        invModel_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invModel_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invModel_jLabel.setText("規格型號");
        invModel_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        invModel_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        invModel_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invModel_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        invModel_jTextField.setPreferredSize(new java.awt.Dimension(600, 30));

        invQuantity_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invQuantity_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invQuantity_jLabel.setText("數量");
        invQuantity_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        invQuantity_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        invQuantity_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invQuantity_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        invQuantity_jTextField.setPreferredSize(new java.awt.Dimension(50, 30));

        location_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        location_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        location_jLabel.setText("所在地");
        location_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        location_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        location_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        location_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        location_jTextField.setPreferredSize(new java.awt.Dimension(350, 30));

        remark_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        remark_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remark_jLabel.setText("備註");
        remark_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        remark_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        remark_jTextArea.setColumns(20);
        remark_jTextArea.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        remark_jTextArea.setRows(5);
        remark_jTextArea.setPreferredSize(new java.awt.Dimension(600, 300));
        jScrollPane2.setViewportView(remark_jTextArea);

        keeper_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        keeper_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keeper_jLabel.setText("保管人");
        keeper_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        keeper_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        keeper_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        keeper_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keeper_jTextField.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comName_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comName_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(depart_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depart_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(location_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(location_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(keeper_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(keeper_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(invName_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(invName_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(invModel_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(invModel_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(invQuantity_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(invQuantity_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(invNum_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(invNum_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(purchase_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(purchase_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(remark_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invNum_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invNum_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchase_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchase_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comName_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comName_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depart_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depart_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(location_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keeper_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keeper_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invName_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invName_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invModel_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invModel_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invQuantity_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invQuantity_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(remark_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("標楷體", 1, 16)); // NOI18N
        jButton1.setText("取消");

        jButton2.setFont(new java.awt.Font("標楷體", 1, 16)); // NOI18N
        jButton2.setText("修改");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 30));

        InvID_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        InvID_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InvID_jLabel.setText("ID");
        InvID_jLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        InvID_jLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        invID_jTextField.setEditable(false);
        invID_jTextField.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invID_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        invID_jTextField.setBorder(null);
        invID_jTextField.setPreferredSize(new java.awt.Dimension(600, 30));

        javax.swing.GroupLayout modifyInvItem_JFrameLayout = new javax.swing.GroupLayout(modifyInvItem_JFrame.getContentPane());
        modifyInvItem_JFrame.getContentPane().setLayout(modifyInvItem_JFrameLayout);
        modifyInvItem_JFrameLayout.setHorizontalGroup(
            modifyInvItem_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(modifyInvItem_JFrameLayout.createSequentialGroup()
                .addGroup(modifyInvItem_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyInvItem_JFrameLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InvID_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invID_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modifyInvItem_JFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        modifyInvItem_JFrameLayout.setVerticalGroup(
            modifyInvItem_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyInvItem_JFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyInvItem_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InvID_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invID_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(modifyInvItem_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        addInvItem_jFrame.setPreferredSize(new java.awt.Dimension(800, 600));
        addInvItem_jFrame.setResizable(false);

        jPanel4.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel3.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("新增");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));

        AssetClass_jComboBox.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        AssetClass_jComboBox.setPreferredSize(new java.awt.Dimension(180, 30));

        AssetClass_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        AssetClass_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AssetClass_jLabel.setText("資產分類");
        AssetClass_jLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        AssetClass_jLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        AssetClass_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        ComCode_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ComCode_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComCode_jLabel.setText("公司別");
        ComCode_jLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        ComCode_jLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        ComCode_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        ComCode_jComboBox.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ComCode_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 休閒", "2 益合", "3 富士(上海)", "4 富士(廣州)", "5 藝禾", "6 鮮匯" }));
        ComCode_jComboBox.setPreferredSize(new java.awt.Dimension(180, 30));

        Accounting_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        Accounting_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Accounting_jLabel.setText("會計科目");
        Accounting_jLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        Accounting_jLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        Accounting_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        Accounting_jComboBox.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        Accounting_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "501 土地", "502 房屋及建築", "531 機器設備", "551 運輸設備", "561 辦公設備", "631 租賃改良", "681 其他設備" }));
        Accounting_jComboBox.setPreferredSize(new java.awt.Dimension(180, 30));

        ClassCode_jLabel.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ClassCode_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassCode_jLabel.setText("分類代碼");
        ClassCode_jLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        ClassCode_jLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        ClassCode_jLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        ClassCode_jComboBox.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ClassCode_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11 土地", "21 房屋及建築", "22 房屋附屬設備", "31 研發設備", "32 倉儲設備", "33 模具", "34 生產設備", "35 生產附屬設備", "41 公務轎車", "42 公務貨車", "43 運輸設備附屬設備", "44 其他運輸設備", "51 事務機器", "52 電話系統", "53 電腦主機", "54 桌上型電腦設備", "55 攜帶型電腦設備", "56 其他電腦硬體設備", "57 視聽設備", "61 裝修工程", "62 維修工程", "71 屏風", "72 藝術家飾", "73 中央空調、冷氣機", "74 家電", "75 安全管理設備", "76 消防設備", "77 雜項購置", "78 椅", "79 桌", "80 櫥櫃" }));
        ClassCode_jComboBox.setPreferredSize(new java.awt.Dimension(180, 30));

        invCheck_btn.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invCheck_btn.setText("檢查");
        invCheck_btn.setMaximumSize(new java.awt.Dimension(100, 30));
        invCheck_btn.setMinimumSize(new java.awt.Dimension(100, 30));
        invCheck_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        invCheck_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invCheck_btnMouseClicked(evt);
            }
        });

        InvCode_TF.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        InvCode_TF.setPreferredSize(new java.awt.Dimension(100, 30));

        assetClass_BG.add(ac1_RB);
        ac1_RB.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ac1_RB.setSelected(true);
        ac1_RB.setText("列帳");
        ac1_RB.setToolTipText("");
        ac1_RB.setMaximumSize(new java.awt.Dimension(180, 30));
        ac1_RB.setMinimumSize(new java.awt.Dimension(180, 30));
        ac1_RB.setName("1"); // NOI18N
        ac1_RB.setPreferredSize(new java.awt.Dimension(180, 30));

        assetClass_BG.add(ac2_RB);
        ac2_RB.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ac2_RB.setText("列管");
        ac2_RB.setMaximumSize(new java.awt.Dimension(180, 30));
        ac2_RB.setMinimumSize(new java.awt.Dimension(180, 30));
        ac2_RB.setName("2"); // NOI18N
        ac2_RB.setPreferredSize(new java.awt.Dimension(180, 30));

        AssetClass_TF.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        AssetClass_TF.setPreferredSize(new java.awt.Dimension(100, 30));

        ComCode_TF.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ComCode_TF.setPreferredSize(new java.awt.Dimension(100, 30));

        Accounting_TF.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        Accounting_TF.setPreferredSize(new java.awt.Dimension(100, 30));

        ClassCode_TF.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        ClassCode_TF.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComCode_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssetClass_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Accounting_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClassCode_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComCode_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AssetClass_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Accounting_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClassCode_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(ac1_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AssetClass_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(ac2_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Accounting_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComCode_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ClassCode_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(invCheck_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(InvCode_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssetClass_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssetClass_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ac1_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssetClass_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComCode_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComCode_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ac2_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComCode_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accounting_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Accounting_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Accounting_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassCode_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassCode_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassCode_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invCheck_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvCode_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addInvItem_jFrameLayout = new javax.swing.GroupLayout(addInvItem_jFrame.getContentPane());
        addInvItem_jFrame.getContentPane().setLayout(addInvItem_jFrameLayout);
        addInvItem_jFrameLayout.setHorizontalGroup(
            addInvItem_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addInvItem_jFrameLayout.setVerticalGroup(
            addInvItem_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addInvItem_jFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("標楷體", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("資產表");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 60));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 40));

        queryInvList_btn.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        queryInvList_btn.setText("查詢");
        queryInvList_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        queryInvList_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryInvList_btnMouseClicked(evt);
            }
        });

        modifyInvItem_btn.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        modifyInvItem_btn.setText("修改");
        modifyInvItem_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        modifyInvItem_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyInvItem_btnMouseClicked(evt);
            }
        });

        addInvItem_btn.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        addInvItem_btn.setText("新增");
        addInvItem_btn.setToolTipText("");
        addInvItem_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        addInvItem_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addInvItem_btnMouseClicked(evt);
            }
        });

        scrappedInvItem_btn.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        scrappedInvItem_btn.setText("報廢");
        scrappedInvItem_btn.setToolTipText("");
        scrappedInvItem_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        scrappedInvItem_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrappedInvItem_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queryInvList_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addInvItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modifyInvItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrappedInvItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryInvList_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyInvItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addInvItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrappedInvItem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        inv_List_Table.setBackground(new java.awt.Color(204, 204, 204));
        inv_List_Table.setFont(new java.awt.Font("標楷體", 0, 18)); // NOI18N
        inv_List_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "公司別", "所屬部門", "資產編號", "購入日期", "資產名稱", "規格型號", "數量", "所在地", "保管人", "備註"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inv_List_Table.setRowHeight(30);
        inv_List_Table.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(inv_List_Table);
        if (inv_List_Table.getColumnModel().getColumnCount() > 0) {
            inv_List_Table.getColumnModel().getColumn(0).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(1).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(2).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(3).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(4).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(5).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(6).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(7).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(8).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(9).setResizable(false);
            inv_List_Table.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTable(){
        ArrayList<inventoryList> inv_List = (ArrayList<inventoryList>) new inventoryListDao().queryTalbe();
        Object[] o = new Object[11];
        
        for(int i=0; i<inv_List.size(); i++){
            o[0]=inv_List.get(i).getInv_Id();
            o[1]=inv_List.get(i).getCompany_Name();
            o[2]=inv_List.get(i).getDepartment_Name();
            o[3]=inv_List.get(i).getInv_Num();
            o[4]=inv_List.get(i).getPurchase_data();
            o[5]=inv_List.get(i).getInv_Name();
            o[6]=inv_List.get(i).getInv_Model();
            o[7]=inv_List.get(i).getInv_Quantity();
            o[8]=inv_List.get(i).getInv_location();
            o[9]=inv_List.get(i).getInv_keeper();
            o[10]=inv_List.get(i).getInv_Remark();
            
            iniTable.showTable(inv_List_Table, o);            
        }
    }
    
    private void setConboBox(){
        DefaultComboBoxModel CBModel = new DefaultComboBoxModel();
        ArrayList<assetsClass> acList = (ArrayList<assetsClass>) new assetsClassDao().queryTalbe();
        Object[] o = new Object[3];
        
        for(int i=0; i<acList.size(); i++){
            o[0]=acList.get(i).getAcID();
            o[1]=acList.get(i).getAcNum();
            o[2]=acList.get(i).getAcName();
            
            AssetClass_jComboBox.addItem(o[1].toString()+""+o[2].toString());          
        }     
    }
    private void queryInvList_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queryInvList_btnMouseClicked
        
        ArrayList<inventoryList> inv_List = (ArrayList<inventoryList>) new inventoryListDao().queryTalbe();
        Object[] o = new Object[11];
        
        for(int i=0; i<inv_List.size(); i++){
            o[0]=inv_List.get(i).getInv_Id();
            o[1]=inv_List.get(i).getCompany_Name();
            o[2]=inv_List.get(i).getDepartment_Name();
            o[3]=inv_List.get(i).getInv_Num();
            o[4]=inv_List.get(i).getPurchase_data();
            o[5]=inv_List.get(i).getInv_Name();
            o[6]=inv_List.get(i).getInv_Model();
            o[7]=inv_List.get(i).getInv_Quantity();
            o[8]=inv_List.get(i).getInv_location();
            o[9]=inv_List.get(i).getInv_keeper();
            o[10]=inv_List.get(i).getInv_Remark();
            
            iniTable.showTable(inv_List_Table, o);            
        }
        
    }//GEN-LAST:event_queryInvList_btnMouseClicked

    private void modifyInvItem_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyInvItem_btnMouseClicked
        setupComponent.JFrameCenter(modifyInvItem_JFrame);
        
        DefaultTableModel model = (DefaultTableModel) inv_List_Table.getModel();
        
        invID_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 0)));
        comName_jTextField.setText((String) model.getValueAt(inv_List_Table.getSelectedRow(), 1));
        depart_jTextField.setText((String) model.getValueAt(inv_List_Table.getSelectedRow(), 2));
        invNum_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 3)));
        purchase_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 4)));
        invName_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 5)));
        invModel_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 6)));
        invQuantity_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 7)));
        location_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 8)));
        keeper_jTextField.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 9)));
        remark_jTextArea.setText(String.valueOf(model.getValueAt(inv_List_Table.getSelectedRow(), 10)));
    }//GEN-LAST:event_modifyInvItem_btnMouseClicked

    private void addInvItem_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addInvItem_btnMouseClicked
        setupComponent.JFrameCenter(addInvItem_jFrame);
        setConboBox();
        
    }//GEN-LAST:event_addInvItem_btnMouseClicked

    private void scrappedInvItem_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrappedInvItem_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scrappedInvItem_btnMouseClicked

    private void invCheck_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invCheck_btnMouseClicked
        String getSelected = String.valueOf(AssetClass_jComboBox.getSelectedItem());       
        String num = getSelected.stripLeading();
        Integer ID = Integer.parseInt(AssetClass_TF.getText()+ComCode_TF.getText()+Accounting_TF.getText()+ClassCode_TF.getText());
        InvCode_TF.setText(new inventoryListDao().queryCheck(AssetClass_TF.getText()+ComCode_TF.getText()+Accounting_TF.getText()+ClassCode_TF.getText()).getInv_Num());
        
        //InvCode_TF.setText(AssetClass_TF.getText()+ComCode_TF.getText()+Accounting_TF.getText()+ClassCode_TF.getText());
        //InvCode_TF.setText(String.valueOf(AssetClass_jComboBox.getSelectedItem()));
        //InvCode_TF.setText(assetClass_BG.getSelection());
    }//GEN-LAST:event_invCheck_btnMouseClicked
    
    //視窗置中
    public final void setCenter(){
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventoryListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventoryListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventoryListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventoryListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventoryListUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Accounting_TF;
    private javax.swing.JComboBox<String> Accounting_jComboBox;
    private javax.swing.JLabel Accounting_jLabel;
    private javax.swing.JTextField AssetClass_TF;
    private javax.swing.JComboBox<String> AssetClass_jComboBox;
    private javax.swing.JLabel AssetClass_jLabel;
    private javax.swing.JTextField ClassCode_TF;
    private javax.swing.JComboBox<String> ClassCode_jComboBox;
    private javax.swing.JLabel ClassCode_jLabel;
    private javax.swing.JTextField ComCode_TF;
    private javax.swing.JComboBox<String> ComCode_jComboBox;
    private javax.swing.JLabel ComCode_jLabel;
    private javax.swing.JTextField InvCode_TF;
    private javax.swing.JLabel InvID_jLabel;
    private javax.swing.JRadioButton ac1_RB;
    private javax.swing.JRadioButton ac2_RB;
    private javax.swing.JButton addInvItem_btn;
    private javax.swing.JFrame addInvItem_jFrame;
    private javax.swing.ButtonGroup assetClass_BG;
    private javax.swing.JLabel comName_jLabel;
    private javax.swing.JTextField comName_jTextField;
    private javax.swing.JLabel depart_jLabel;
    private javax.swing.JTextField depart_jTextField;
    private javax.swing.JDialog errMsg_jDialog;
    private javax.swing.JButton invCheck_btn;
    private javax.swing.JTextField invID_jTextField;
    private javax.swing.JLabel invModel_jLabel;
    private javax.swing.JTextField invModel_jTextField;
    private javax.swing.JLabel invName_jLabel;
    private javax.swing.JTextField invName_jTextField;
    private javax.swing.JLabel invNum_jLabel;
    private javax.swing.JTextField invNum_jTextField;
    private javax.swing.JLabel invQuantity_jLabel;
    private javax.swing.JTextField invQuantity_jTextField;
    private javax.swing.JTable inv_List_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel keeper_jLabel;
    private javax.swing.JTextField keeper_jTextField;
    private javax.swing.JLabel location_jLabel;
    private javax.swing.JTextField location_jTextField;
    private javax.swing.JFrame modifyInvItem_JFrame;
    private javax.swing.JButton modifyInvItem_btn;
    private javax.swing.JLabel purchase_jLabel;
    private javax.swing.JTextField purchase_jTextField;
    private javax.swing.JButton queryInvList_btn;
    private javax.swing.JLabel remark_jLabel;
    private javax.swing.JTextArea remark_jTextArea;
    private javax.swing.JButton scrappedInvItem_btn;
    // End of variables declaration//GEN-END:variables
}
