/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conntroller;

import Dao.inventoryListDao;
import Methods.iniTable;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import model.inventoryList;

/**
 *
 * @author luther
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setCenter();
        iniTable.iniListTB(jTable1);
        setBlank();

        invManager_pl.setVisible(false);
        Inv_Info_PL.setVisible(false);
        Inv_Mod_PL.setVisible(false);

        invList_pl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        invManager_btn = new javax.swing.JButton();
        invList_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        invManager_pl = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Inv_Info_PL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Inv_Num_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Inv_CP_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Inv_DP_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Inv_KP_TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Inv_PHD_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Inv_LC_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Inv_Name_TF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Inv_Model_TA = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Inv_QT_TF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Inv_RMK_TA = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        infoOption_pl = new javax.swing.JPanel();
        InfoToMod_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        modOption_pl = new javax.swing.JPanel();
        ModToInfo_btn = new javax.swing.JButton();
        sendToUpdata_btn = new javax.swing.JButton();
        Inv_Mod_PL = new javax.swing.JPanel();
        invList_pl = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        invUsed_pl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        invUsed_list = new javax.swing.JList<>();
        invSold_pl = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1500, 844));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1488, 832));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 534));

        invManager_btn.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invManager_btn.setText("資產管理");
        invManager_btn.setBorder(null);
        invManager_btn.setBorderPainted(false);
        invManager_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        invManager_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invManager_btnMouseClicked(evt);
            }
        });

        invList_btn.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        invList_btn.setText("資產列表");
        invList_btn.setToolTipText("");
        invList_btn.setPreferredSize(new java.awt.Dimension(104, 30));
        invList_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invList_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(invList_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invManager_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invList_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        invManager_pl.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("新宋体", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1046, 300));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("標楷體", 1, 14))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(120, 406));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(900, 406));
        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        Inv_Info_PL.setBackground(new java.awt.Color(255, 255, 255));
        Inv_Info_PL.setPreferredSize(new java.awt.Dimension(900, 382));

        jLabel1.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inv_Num");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_Num_TF.setEditable(false);
        Inv_Num_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_Num_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_Num_TF.setText("jTextField1");
        Inv_Num_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_Num_TF.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabel2.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inv_CP");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_CP_TF.setEditable(false);
        Inv_CP_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_CP_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_CP_TF.setText("jTextField1");
        Inv_CP_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_CP_TF.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabel3.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inv_DP");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_DP_TF.setEditable(false);
        Inv_DP_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_DP_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_DP_TF.setText("jTextField1");
        Inv_DP_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_DP_TF.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabel4.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inv_KP");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_KP_TF.setEditable(false);
        Inv_KP_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_KP_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_KP_TF.setText("jTextField1");
        Inv_KP_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_KP_TF.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabel5.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inv_PHD");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_PHD_TF.setEditable(false);
        Inv_PHD_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_PHD_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_PHD_TF.setText("jTextField1");
        Inv_PHD_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_PHD_TF.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabel6.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inv_LC");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_LC_TF.setEditable(false);
        Inv_LC_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_LC_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_LC_TF.setText("jTextField1");
        Inv_LC_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_LC_TF.setPreferredSize(new java.awt.Dimension(240, 30));

        jLabel7.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Inv_Name");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_Name_TF.setEditable(false);
        Inv_Name_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_Name_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_Name_TF.setText("jTextField1");
        Inv_Name_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_Name_TF.setPreferredSize(new java.awt.Dimension(180, 30));

        jLabel8.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Inv_Model");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_Model_TA.setEditable(false);
        Inv_Model_TA.setColumns(20);
        Inv_Model_TA.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_Model_TA.setRows(5);
        Inv_Model_TA.setAutoscrolls(false);
        Inv_Model_TA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(Inv_Model_TA);

        jLabel9.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Inv_QT");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));

        Inv_QT_TF.setEditable(false);
        Inv_QT_TF.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_QT_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv_QT_TF.setText("jTextField1");
        Inv_QT_TF.setMinimumSize(new java.awt.Dimension(64, 30));
        Inv_QT_TF.setPreferredSize(new java.awt.Dimension(60, 30));

        Inv_RMK_TA.setEditable(false);
        Inv_RMK_TA.setColumns(20);
        Inv_RMK_TA.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        Inv_RMK_TA.setRows(5);
        jScrollPane3.setViewportView(Inv_RMK_TA);

        jLabel10.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Inv_RMK");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.OverlayLayout(jPanel5));

        infoOption_pl.setBackground(new java.awt.Color(255, 255, 255));

        InfoToMod_btn.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        InfoToMod_btn.setText("修改");
        InfoToMod_btn.setPreferredSize(new java.awt.Dimension(72, 30));
        InfoToMod_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoToMod_btnMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        jButton2.setText("報廢");
        jButton2.setPreferredSize(new java.awt.Dimension(72, 30));

        javax.swing.GroupLayout infoOption_plLayout = new javax.swing.GroupLayout(infoOption_pl);
        infoOption_pl.setLayout(infoOption_plLayout);
        infoOption_plLayout.setHorizontalGroup(
            infoOption_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoOption_plLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoOption_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoToMod_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        infoOption_plLayout.setVerticalGroup(
            infoOption_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoOption_plLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(InfoToMod_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(infoOption_pl);

        modOption_pl.setBackground(new java.awt.Color(255, 255, 255));

        ModToInfo_btn.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        ModToInfo_btn.setText("取消");
        ModToInfo_btn.setPreferredSize(new java.awt.Dimension(72, 30));
        ModToInfo_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModToInfo_btnMouseClicked(evt);
            }
        });

        sendToUpdata_btn.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        sendToUpdata_btn.setText("送出");
        sendToUpdata_btn.setPreferredSize(new java.awt.Dimension(72, 30));

        javax.swing.GroupLayout modOption_plLayout = new javax.swing.GroupLayout(modOption_pl);
        modOption_pl.setLayout(modOption_plLayout);
        modOption_plLayout.setHorizontalGroup(
            modOption_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modOption_plLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modOption_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendToUpdata_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModToInfo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        modOption_plLayout.setVerticalGroup(
            modOption_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modOption_plLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(ModToInfo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendToUpdata_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(modOption_pl);

        javax.swing.GroupLayout Inv_Info_PLLayout = new javax.swing.GroupLayout(Inv_Info_PL);
        Inv_Info_PL.setLayout(Inv_Info_PLLayout);
        Inv_Info_PLLayout.setHorizontalGroup(
            Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                        .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Inv_Info_PLLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Inv_Info_PLLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Inv_Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inv_QT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                    .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                        .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inv_KP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inv_LC_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inv_CP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inv_DP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inv_Num_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inv_PHD_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Inv_Info_PLLayout.setVerticalGroup(
            Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inv_Info_PLLayout.createSequentialGroup()
                        .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_Num_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_PHD_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_CP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_DP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_KP_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_LC_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                                .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Inv_QT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Inv_Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Inv_Info_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(Inv_Info_PLLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane3)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8.add(Inv_Info_PL);

        Inv_Mod_PL.setBackground(new java.awt.Color(255, 255, 255));
        Inv_Mod_PL.setPreferredSize(new java.awt.Dimension(900, 382));

        javax.swing.GroupLayout Inv_Mod_PLLayout = new javax.swing.GroupLayout(Inv_Mod_PL);
        Inv_Mod_PL.setLayout(Inv_Mod_PLLayout);
        Inv_Mod_PLLayout.setHorizontalGroup(
            Inv_Mod_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
        );
        Inv_Mod_PLLayout.setVerticalGroup(
            Inv_Mod_PLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jPanel8.add(Inv_Mod_PL);

        javax.swing.GroupLayout invManager_plLayout = new javax.swing.GroupLayout(invManager_pl);
        invManager_pl.setLayout(invManager_plLayout);
        invManager_plLayout.setHorizontalGroup(
            invManager_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invManager_plLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invManager_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1328, Short.MAX_VALUE)
                    .addGroup(invManager_plLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)))
                .addContainerGap())
        );
        invManager_plLayout.setVerticalGroup(
            invManager_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invManager_plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invManager_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(invManager_pl);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        invUsed_pl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        invUsed_pl.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N

        invUsed_list.setFont(new java.awt.Font("標楷體", 1, 14)); // NOI18N
        invUsed_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(invUsed_list);

        javax.swing.GroupLayout invUsed_plLayout = new javax.swing.GroupLayout(invUsed_pl);
        invUsed_pl.setLayout(invUsed_plLayout);
        invUsed_plLayout.setHorizontalGroup(
            invUsed_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invUsed_plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
                .addContainerGap())
        );
        invUsed_plLayout.setVerticalGroup(
            invUsed_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invUsed_plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("列表", invUsed_pl);

        invSold_pl.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N

        javax.swing.GroupLayout invSold_plLayout = new javax.swing.GroupLayout(invSold_pl);
        invSold_pl.setLayout(invSold_plLayout);
        invSold_plLayout.setHorizontalGroup(
            invSold_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1326, Short.MAX_VALUE)
        );
        invSold_plLayout.setVerticalGroup(
            invSold_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("出售", invSold_pl);

        jPanel12.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1326, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("報廢", jPanel12);

        javax.swing.GroupLayout invList_plLayout = new javax.swing.GroupLayout(invList_pl);
        invList_pl.setLayout(invList_plLayout);
        invList_plLayout.setHorizontalGroup(
            invList_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invList_plLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invList_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        invList_plLayout.setVerticalGroup(
            invList_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invList_plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel4.add(invList_pl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<inventoryList> invList = (ArrayList<inventoryList>) new inventoryListDao().queryTable();

    inventoryList inv = null;

    private void showTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Object[] o = new Object[6];

        invList.stream().map(inv -> {
            o[0] = String.format("%04d", inv.getInv_Id());
            return inv;
        }).map(inv -> {
            o[1] = inv.getCompany_Name();
            return inv;
        }).map(inv -> {
            o[2] = inv.getDepartment_Name();
            return inv;
        }).map(inv -> {
            o[3] = inv.getInv_Num();
            return inv;
        }).map(inv -> {
            o[4] = inv.getInv_Name();
            return inv;
        }).map(inv -> {
            o[5] = inv.getInv_Model();
            return inv;
        }).forEachOrdered(_item -> {
            model.addRow(o);
        });

    }

    private void setBlank() {
        Inv_Num_TF.setText("");
        Inv_CP_TF.setText("");
        Inv_DP_TF.setText("");
        Inv_KP_TF.setText("");
        Inv_LC_TF.setText("");
        Inv_PHD_TF.setText("");
        Inv_QT_TF.setText("");
        Inv_Name_TF.setText("");
        Inv_Model_TA.setText("");
        Inv_RMK_TA.setText("");
    }

    private void setEditable() {
        Inv_Num_TF.setEditable(true);
        Inv_CP_TF.setEditable(true);
        Inv_DP_TF.setEditable(true);
        Inv_KP_TF.setEditable(true);
        Inv_LC_TF.setEditable(true);
        Inv_PHD_TF.setEditable(true);
        Inv_QT_TF.setEditable(true);
        Inv_Name_TF.setEditable(true);
        Inv_Model_TA.setEditable(true);
        Inv_RMK_TA.setEditable(true);
    }

    private void setEditdisable() {
        Inv_Num_TF.setEditable(false);
        Inv_CP_TF.setEditable(false);
        Inv_DP_TF.setEditable(false);
        Inv_KP_TF.setEditable(false);
        Inv_LC_TF.setEditable(false);
        Inv_PHD_TF.setEditable(false);
        Inv_QT_TF.setEditable(false);
        Inv_Name_TF.setEditable(false);
        Inv_Model_TA.setEditable(false);
        Inv_RMK_TA.setEditable(false);
    }
    
    private void setNoChange(){
        Inv_Num_TF.setText(inv.getInv_Num());
        Inv_CP_TF.setText(inv.getCompany_Name());
        Inv_DP_TF.setText(inv.getDepartment_Name());
        Inv_KP_TF.setText(inv.getInv_keeper());
        Inv_LC_TF.setText(inv.getInv_location());
        Inv_PHD_TF.setText(inv.getPurchase_data());
        Inv_QT_TF.setText(String.valueOf(inv.getInv_Quantity()));
        Inv_Name_TF.setText(inv.getInv_Name());
        Inv_Model_TA.setText(inv.getInv_Model());
        Inv_RMK_TA.setText(inv.getInv_Remark());
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:              
        Inv_Num_TF.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        Inv_CP_TF.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
        Inv_DP_TF.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        Inv_Name_TF.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
        Inv_Model_TA.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5)));

        Integer invID = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

        for (int i = 0; i < invList.size(); i++) {
            if (invID.equals(invList.get(i).getInv_Id())) {
                Inv_PHD_TF.setText(invList.get(i).getPurchase_data());
                Inv_KP_TF.setText(invList.get(i).getInv_keeper());
                Inv_LC_TF.setText(invList.get(i).getInv_location());
                Inv_QT_TF.setText(String.valueOf(invList.get(i).getInv_Quantity()));
                Inv_RMK_TA.setText(invList.get(i).getInv_Remark());

                inv = new inventoryList(
                        invList.get(i).getInv_Quantity(),
                        invList.get(i).getCompany_Name(),
                        invList.get(i).getDepartment_Name(),
                        invList.get(i).getInv_Num(),
                        invList.get(i).getPurchase_data(),
                        invList.get(i).getInv_Name(),
                        invList.get(i).getInv_Model(),
                        invList.get(i).getInv_location(),
                        invList.get(i).getInv_keeper(),
                        invList.get(i).getInv_Remark()
                );
            }
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void invManager_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invManager_btnMouseClicked
        // TODO add your handling code here:
        iniTable.iniListTB(jTable1);
        showTable();

        invList_pl.setVisible(false);
        invManager_pl.setVisible(true);
        Inv_Info_PL.setVisible(true);

    }//GEN-LAST:event_invManager_btnMouseClicked

    private void ModToInfo_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModToInfo_btnMouseClicked
        // TODO add your handling code here:
        modOption_pl.setVisible(false);
        infoOption_pl.setVisible(true);
        Inv_Num_TF.setEditable(false);
        
        setNoChange();      
        setEditdisable();
    }//GEN-LAST:event_ModToInfo_btnMouseClicked

    private void InfoToMod_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoToMod_btnMouseClicked
        // TODO add your handling code here:
        infoOption_pl.setVisible(false);
        modOption_pl.setVisible(true);
        Inv_Num_TF.setEditable(true);

        setEditable();
    }//GEN-LAST:event_InfoToMod_btnMouseClicked

    private void invList_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invList_btnMouseClicked
        // TODO add your handling code here:
        invManager_pl.setVisible(false);
        invList_pl.setVisible(true);

        DefaultListModel model = new DefaultListModel();

        invList.forEach(inv -> {
            model.addElement(inv.getInv_Num() + " " + inv.getInv_Name());
        });

        invUsed_list.setModel(model);
    }//GEN-LAST:event_invList_btnMouseClicked

    //視窗置中
    public final void setCenter() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoToMod_btn;
    private javax.swing.JTextField Inv_CP_TF;
    private javax.swing.JTextField Inv_DP_TF;
    private javax.swing.JPanel Inv_Info_PL;
    private javax.swing.JTextField Inv_KP_TF;
    private javax.swing.JTextField Inv_LC_TF;
    private javax.swing.JPanel Inv_Mod_PL;
    private javax.swing.JTextArea Inv_Model_TA;
    private javax.swing.JTextField Inv_Name_TF;
    private javax.swing.JTextField Inv_Num_TF;
    private javax.swing.JTextField Inv_PHD_TF;
    private javax.swing.JTextField Inv_QT_TF;
    private javax.swing.JTextArea Inv_RMK_TA;
    private javax.swing.JButton ModToInfo_btn;
    private javax.swing.JPanel infoOption_pl;
    private javax.swing.JButton invList_btn;
    private javax.swing.JPanel invList_pl;
    private javax.swing.JButton invManager_btn;
    private javax.swing.JPanel invManager_pl;
    private javax.swing.JPanel invSold_pl;
    private javax.swing.JList<String> invUsed_list;
    private javax.swing.JPanel invUsed_pl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel modOption_pl;
    private javax.swing.JButton sendToUpdata_btn;
    // End of variables declaration//GEN-END:variables
}
